### ISSUE TITLE
快速开始 - TeXt Theme

### ISSUE THREAD

**Issue by kitian616** [kitian616/gitalk-demo#48]
https://tianqi.name/jekyll-TeXt-theme/docs/zh/quick-start 

 A customizable Jekyll theme for your blog or site

**Comment by 2018liuyi** [comment]
111

**Comment by unclefung** [comment]
想请教一下作者，我下载主题后部署在一台Linux的VPS里面，关于gitalk是按照配置里面填写的，但不知道为什么一直都没有成功。

**Comment by heytxz** [comment]
感谢作者提供的优秀作品！

**Comment by Stephenzho** [comment]
为啥没有页脚的功能，备案信息等

**Comment by Envov** [comment]
#### 很强

**Comment by Envov** [comment]
# 11

**Comment by jxylon** [comment]
我先从Github fork您的项目，然后安装开发环境，在本地预览这步安装了ruby和jekyll，运行bundle install --path vendor/bundle这段命令时出现了下面的错误，有什么解决方法，谢谢。
```
Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'E:/Github/jxylon.github.io'
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:179:in `setup'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:100:in `process'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
        from E:/Github/jxylon.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<main>'
```
